import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Fonts for the PDF (the app's Lora and Nunito, bundled, so it works offline).
class SummaryPdfFonts {
  const SummaryPdfFonts({required this.heading, required this.body, required this.bold});

  final pw.Font heading;
  final pw.Font body;
  final pw.Font bold;

  static Future<SummaryPdfFonts> load() async {
    Future<pw.Font> font(String file) async => pw.Font.ttf(await rootBundle.load('assets/fonts/$file'));
    return SummaryPdfFonts(
      heading: await font('Lora-SemiBold.ttf'),
      body: await font('Nunito-Regular.ttf'),
      bold: await font('Nunito-Bold.ttf'),
    );
  }
}

const _navy = PdfColor.fromInt(0xFF34496E);
const _muted = PdfColor.fromInt(0xFF5F6572);
const _line = PdfColor.fromInt(0xFFE8DFD0);
const _cream = PdfColor.fromInt(0xFFFBF7F0);

/// The doctor summary as an A4 PDF. [text] is the English summary: blocks
/// separated by blank lines; the first block is the title and details, each
/// later block starts with its heading, and "• " lines are bullets.
Future<Uint8List> buildSummaryPdf(
  String text, {
  required SummaryPdfFonts fonts,
  required String generatedOn,
}) async {
  final blocks = <List<String>>[[]];
  for (final line in text.split('\n')) {
    if (line.trim().isEmpty) {
      if (blocks.last.isNotEmpty) blocks.add([]);
    } else {
      blocks.last.add(line);
    }
  }
  if (blocks.last.isEmpty) blocks.removeLast();

  final body = pw.TextStyle(font: fonts.body, fontSize: 10.5, lineSpacing: 2);
  final bold = pw.TextStyle(font: fonts.bold, fontSize: 10.5);
  final heading = pw.TextStyle(font: fonts.heading, fontSize: 13, color: _navy);

  pw.Widget lineWidget(String line) => line.startsWith('• ')
      ? pw.Padding(
          padding: const pw.EdgeInsets.only(left: 6, bottom: 3),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('•  ', style: bold),
              pw.Expanded(child: pw.Text(line.substring(2), style: body)),
            ],
          ),
        )
      : pw.Padding(padding: const pw.EdgeInsets.only(bottom: 3), child: pw.Text(line, style: body));

  final doc = pw.Document(title: blocks.isEmpty ? 'Health summary' : blocks.first.first, author: 'Palna');
  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.fromLTRB(40, 36, 40, 36),
      header: (context) => pw.Container(
        padding: const pw.EdgeInsets.only(bottom: 8),
        margin: const pw.EdgeInsets.only(bottom: 12),
        decoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: _line))),
        child: pw.Row(
          children: [
            pw.Text('Palna', style: pw.TextStyle(font: fonts.heading, fontSize: 14, color: _navy)),
            pw.SizedBox(width: 8),
            pw.Text('Mother & Baby Care', style: pw.TextStyle(font: fonts.body, fontSize: 9, color: _muted)),
            pw.Spacer(),
            pw.Text('palnacare.com', style: pw.TextStyle(font: fonts.body, fontSize: 9, color: _muted)),
          ],
        ),
      ),
      footer: (context) => pw.Row(
        children: [
          pw.Expanded(
            child: pw.Text(
              'Generated by Palna on $generatedOn from records kept by the family. '
              'Not a medical record or a diagnosis.',
              style: pw.TextStyle(font: fonts.body, fontSize: 8, color: _muted),
            ),
          ),
          pw.Text(
            '${context.pageNumber} / ${context.pagesCount}',
            style: pw.TextStyle(font: fonts.body, fontSize: 8, color: _muted),
          ),
        ],
      ),
      build: (context) => [
        for (final (i, block) in blocks.indexed)
          if (i == 0)
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(14),
              margin: const pw.EdgeInsets.only(bottom: 14),
              decoration: pw.BoxDecoration(color: _cream, borderRadius: pw.BorderRadius.circular(8)),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(block.first, style: pw.TextStyle(font: fonts.heading, fontSize: 18, color: _navy)),
                  pw.SizedBox(height: 6),
                  for (final line in block.skip(1)) lineWidget(line),
                ],
              ),
            )
          else
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 12),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(block.first, style: heading),
                  pw.SizedBox(height: 4),
                  for (final line in block.skip(1)) lineWidget(line),
                ],
              ),
            ),
      ],
    ),
  );
  return doc.save();
}
