import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../l10n/app_localizations.dart';

// Guides that ship inside the app (assets/*.json, generated by
// tool/content/*.py). Every text comes in three languages.

/// A text in English, Urdu and Roman Urdu.
class LocalText {
  const LocalText(this._byLocale);

  final Map<String, String> _byLocale;

  factory LocalText.fromJson(Object? json) => LocalText((json as Map).cast<String, String>());

  String of(AppLocalizations l10n) => _byLocale[l10n.localeName] ?? _byLocale['en'] ?? '';

  String get english => _byLocale['en'] ?? '';
}

class Food {
  const Food({
    required this.id,
    required this.category,
    required this.fromMonths,
    required this.allergen,
    required this.choking,
    required this.name,
    required this.prep,
  });

  final String id;
  final String category;
  final int fromMonths;

  /// Allergen group (e.g. 'egg', 'peanut'), or null.
  final String? allergen;
  final bool choking;
  final LocalText name;
  final LocalText prep;

  factory Food.fromJson(Map<String, dynamic> json) => Food(
        id: json['id'] as String,
        category: json['category'] as String,
        fromMonths: json['fromMonths'] as int,
        allergen: json['allergen'] as String?,
        choking: json['choking'] as bool,
        name: LocalText.fromJson(json['name']),
        prep: LocalText.fromJson(json['prep']),
      );
}

class FoodGuide {
  const FoodGuide({
    required this.foods,
    required this.allergens,
    required this.readiness,
    required this.stages,
    required this.rules,
    required this.allergenAdvice,
    required this.reactionSigns,
    required this.myths,
    required this.sources,
    this.vegFirst,
    this.recipes = const [],
  });

  final List<Food> foods;

  /// Allergen group id to its name, in display order.
  final Map<String, LocalText> allergens;
  final LocalText readiness;
  final List<LocalText> stages;
  final List<LocalText> rules;
  final LocalText allergenAdvice;
  final LocalText reactionSigns;
  final List<({LocalText belief, LocalText evidence})> myths;
  final String sources;

  /// "Start with vegetables" advice.
  final LocalText? vegFirst;

  final List<Recipe> recipes;

  Food? food(String id) => foods.where((f) => f.id == id).firstOrNull;

  factory FoodGuide.fromJson(Map<String, dynamic> json) {
    final g = json['guides'] as Map<String, dynamic>;
    return FoodGuide(
      foods: [for (final f in json['foods'] as List) Food.fromJson(f as Map<String, dynamic>)],
      allergens: {
        for (final e in (json['allergens'] as Map<String, dynamic>).entries) e.key: LocalText.fromJson(e.value),
      },
      readiness: LocalText.fromJson(g['readiness']),
      stages: [for (final s in g['stages'] as List) LocalText.fromJson((s as Map)['text'])],
      rules: [for (final r in g['rules'] as List) LocalText.fromJson(r)],
      allergenAdvice: LocalText.fromJson(g['allergenAdvice']),
      reactionSigns: LocalText.fromJson(g['reactionSigns']),
      myths: [
        for (final m in g['myths'] as List)
          (belief: LocalText.fromJson((m as Map)['belief']), evidence: LocalText.fromJson(m['evidence'])),
      ],
      sources: g['sources'] as String,
      vegFirst: g['vegFirst'] == null ? null : LocalText.fromJson(g['vegFirst']),
      recipes: [for (final r in (json['recipes'] as List?) ?? const []) Recipe.fromJson(r as Map<String, dynamic>)],
    );
  }
}

/// A home-style recipe for babies from [fromMonths].
class Recipe {
  const Recipe({
    required this.id,
    required this.fromMonths,
    required this.name,
    required this.ingredients,
    required this.steps,
    this.allergens = const [],
    this.foods = const [],
  });

  final String id;
  final int fromMonths;
  final LocalText name;
  final List<LocalText> ingredients;
  final List<LocalText> steps;

  /// Allergen group ids (see [FoodGuide.allergens]).
  final List<String> allergens;

  /// Food ids used (see [FoodGuide.foods]).
  final List<String> foods;

  factory Recipe.fromJson(Map<String, dynamic> json) => Recipe(
        id: json['id'] as String,
        fromMonths: json['fromMonths'] as int,
        name: LocalText.fromJson(json['name']),
        ingredients: [for (final i in json['ingredients'] as List) LocalText.fromJson(i)],
        steps: [for (final s in json['steps'] as List) LocalText.fromJson(s)],
        allergens: [for (final a in (json['allergens'] as List?) ?? const []) a as String],
        foods: [for (final f in (json['foods'] as List?) ?? const []) f as String],
      );
}

class Milestone {
  const Milestone({required this.id, required this.area, required this.text});

  final String id;

  /// 'social', 'language', 'cognitive' or 'movement'.
  final String area;
  final LocalText text;
}

class MilestoneAge {
  const MilestoneAge({required this.months, required this.milestones, required this.tips});

  final int months;
  final List<Milestone> milestones;
  final List<LocalText> tips;
}

class MilestoneGuide {
  const MilestoneGuide({required this.ages, required this.intro, required this.actEarly, required this.source});

  final List<MilestoneAge> ages;
  final LocalText intro;
  final LocalText actEarly;
  final String source;

  factory MilestoneGuide.fromJson(Map<String, dynamic> json) {
    final g = json['guide'] as Map<String, dynamic>;
    return MilestoneGuide(
      ages: [
        for (final a in json['ages'] as List)
          MilestoneAge(
            months: (a as Map)['months'] as int,
            milestones: [
              for (final m in a['milestones'] as List)
                Milestone(id: (m as Map)['id'] as String, area: m['area'] as String, text: LocalText.fromJson(m['text'])),
            ],
            tips: [for (final t in a['tips'] as List) LocalText.fromJson(t)],
          ),
      ],
      intro: LocalText.fromJson(g['intro']),
      actEarly: LocalText.fromJson(g['actEarly']),
      source: g['source'] as String,
    );
  }
}

Future<Map<String, dynamic>> _loadJson(String asset) async =>
    jsonDecode(await rootBundle.loadString(asset)) as Map<String, dynamic>;

final foodGuideProvider = FutureProvider((ref) async => FoodGuide.fromJson(await _loadJson('assets/foods.json')));

final milestoneGuideProvider =
    FutureProvider((ref) async => MilestoneGuide.fromJson(await _loadJson('assets/milestones.json')));
